// src/main/webapp/app/entities/address/address-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IAddress } from 'app/shared/model/address.model';

@Component({
  selector: 'bpf-address-detail',
  templateUrl: './address-detail.component.html'
})
export class AddressDetailComponent implements OnInit {
  address: IAddress;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ address }) => {
      this.address = address;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="address">
            <h2><span jhiTranslate="mySimpleShopApp.address.detail.title">Address</span> {{address.id}}</h2>
            <hr>
            <bpf-alert-error></bpf-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="mySimpleShopApp.address.addressLine1">Address Line 1</span></dt>
                <dd>
                    <span>{{address.addressLine1}}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.address.addressLine2">Address Line 2</span></dt>
                <dd>
                    <span>{{address.addressLine2}}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.address.city">City</span></dt>
                <dd>
                    <span>{{address.city}}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.address.postalCode">Postal Code</span></dt>
                <dd>
                    <span>{{address.postalCode}}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.address.user">User</span></dt>
                <dd>
                    {{address.userLogin}}
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/address', address.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/address/address-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './address.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const AddressDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const addressEntity = useAppSelector(state => state.address.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="addressDetailsHeading">
          <Translate contentKey="mySimpleShopApp.address.detail.title">Address</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{addressEntity.id}</dd>
          <dt>
            <span id="addressLine1">
              <Translate contentKey="mySimpleShopApp.address.addressLine1">Address Line 1</Translate>
            </span>
          </dt>
          <dd>{addressEntity.addressLine1}</dd>
          <dt>
            <span id="addressLine2">
              <Translate contentKey="mySimpleShopApp.address.addressLine2">Address Line 2</Translate>
            </span>
          </dt>
          <dd>{addressEntity.addressLine2}</dd>
          <dt>
            <span id="city">
              <Translate contentKey="mySimpleShopApp.address.city">City</Translate>
            </span>
          </dt>
          <dd>{addressEntity.city}</dd>
          <dt>
            <span id="postalCode">
              <Translate contentKey="mySimpleShopApp.address.postalCode">Postal Code</Translate>
            </span>
          </dt>
          <dd>{addressEntity.postalCode}</dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.address.user">User</Translate>
          </dt>
          <dd>{addressEntity.user ? addressEntity.user.login : ''}</dd>
        </dl>
        <Button tag={Link} to="/address" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/address/${addressEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default AddressDetail;
