// src/main/webapp/app/entities/shipment/shipment.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IShipment } from 'app/shared/model/shipment.model';
import { ShipmentService } from './shipment.service';
import { ShipmentDeleteDialogComponent } from './shipment-delete-dialog.component';

@Component({
  selector: 'bpf-shipment',
  templateUrl: './shipment.component.html',
})
export class ShipmentComponent implements OnInit, OnDestroy {
  shipments?: IShipment[];
  eventSubscriber?: Subscription;

  constructor(protected shipmentService: ShipmentService, protected eventManager: JhiEventManager, protected modalService: NgbModal) {}

  loadAll(): void {
    this.shipmentService.query().subscribe((res: HttpResponse<IShipment[]>) => (this.shipments = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInShipments();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IShipment): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInShipments(): void {
    this.eventSubscriber = this.eventManager.subscribe('shipmentListModification', () => this.loadAll());
  }

  delete(shipment: IShipment): void {
    const modalRef = this.modalService.open(ShipmentDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.shipment = shipment;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="mySimpleShopApp.shipment.home.title">Shipments</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-shipment" [routerLink]="['/shipment/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="mySimpleShopApp.shipment.home.createLabel">
            Create a new Shipment
            </span>
        </button>
    </h2>

    <bpf-alert-error></bpf-alert-error>

    <bpf-alert></bpf-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="shipments?.length === 0">
        <span jhiTranslate="mySimpleShopApp.shipment.home.notFound">No shipments found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="shipments && shipments.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shipment.shippedAt">Shipped At</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shipment.order">Order</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shipment.shippedBy">Shipped By</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let shipment of shipments ;trackBy: trackId">
                    <td><a [routerLink]="['/shipment', shipment.id, 'view']">{{ shipment.id }}</a></td>
                    <td>{{ shipment.shippedAt | date:'mediumDate' }}</td>
                    <td>
                        <div *ngIf="shipment.orderId">
                            <a [routerLink]="['/shopping-order', shipment.orderId , 'view']" >{{ shipment.orderName }}</a>
                        </div>
                    </td>
                    <td>
                        {{ shipment.shippedByLogin }}
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/shipment', shipment.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/shipment', shipment.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(shipment)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/shipment/shipment.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './shipment.reducer';
import { IShipment } from 'app/shared/model/shipment.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const Shipment = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const shipmentList = useAppSelector(state => state.shipment.entities);
  const loading = useAppSelector(state => state.shipment.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="shipment-heading" data-cy="ShipmentHeading">
        <Translate contentKey="mySimpleShopApp.shipment.home.title">Shipments</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="mySimpleShopApp.shipment.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="mySimpleShopApp.shipment.home.createLabel">Create new Shipment</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {shipmentList && shipmentList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="mySimpleShopApp.shipment.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shipment.shippedAt">Shipped At</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shipment.order">Order</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shipment.shippedBy">Shipped By</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {shipmentList.map((shipment, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${shipment.id}`} color="link" size="sm">
                      {shipment.id}
                    </Button>
                  </td>
                  <td>
                    {shipment.shippedAt ? <TextFormat type="date" value={shipment.shippedAt} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{shipment.order ? <Link to={`shopping-order/${shipment.order.id}`}>{shipment.order.name}</Link> : ''}</td>
                  <td>{shipment.shippedBy ? shipment.shippedBy.login : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${shipment.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${shipment.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${shipment.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="mySimpleShopApp.shipment.home.notFound">No Shipments found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Shipment;
