// src/main/webapp/app/entities/shipment/shipment-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './shipment.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ShipmentDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const shipmentEntity = useAppSelector(state => state.shipment.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="shipmentDetailsHeading">
          <Translate contentKey="mySimpleShopApp.shipment.detail.title">Shipment</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{shipmentEntity.id}</dd>
          <dt>
            <span id="shippedAt">
              <Translate contentKey="mySimpleShopApp.shipment.shippedAt">Shipped At</Translate>
            </span>
          </dt>
          <dd>
            {shipmentEntity.shippedAt ? <TextFormat value={shipmentEntity.shippedAt} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.shipment.order">Order</Translate>
          </dt>
          <dd>{shipmentEntity.order ? shipmentEntity.order.name : ''}</dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.shipment.shippedBy">Shipped By</Translate>
          </dt>
          <dd>{shipmentEntity.shippedBy ? shipmentEntity.shippedBy.login : ''}</dd>
        </dl>
        <Button tag={Link} to="/shipment" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/shipment/${shipmentEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ShipmentDetail;

// src/main/webapp/app/entities/shipment/shipment-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IShipment } from 'app/shared/model/shipment.model';

@Component({
  selector: 'bpf-shipment-detail',
  templateUrl: './shipment-detail.component.html',
})
export class ShipmentDetailComponent implements OnInit {
  shipment: IShipment | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ shipment }) => (this.shipment = shipment));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="shipment">
            <h2><span jhiTranslate="mySimpleShopApp.shipment.detail.title">Shipment</span> {{ shipment.id }}</h2>

            <hr>

            <bpf-alert-error></bpf-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="mySimpleShopApp.shipment.shippedAt">Shipped At</span></dt>
                <dd>
                    <span>{{ shipment.shippedAt }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.shipment.order">Order</span></dt>
                <dd>
                    <div *ngIf="shipment.orderId">
                        <a [routerLink]="['/shopping-order', shipment.orderId, 'view']">{{ shipment.orderName }}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.shipment.shippedBy">Shipped By</span></dt>
                <dd>
                    {{ shipment.shippedByLogin }}
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/shipment', shipment.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
