// src/main/webapp/app/entities/shipment/shipment-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { getEntities as getShoppingOrders } from 'app/entities/shopping-order/shopping-order.reducer';
import { IUser } from 'app/shared/model/user.model';
import { getUsers } from 'app/modules/administration/user-management/user-management.reducer';
import { getEntity, updateEntity, createEntity, reset } from './shipment.reducer';
import { IShipment } from 'app/shared/model/shipment.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IShipmentUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ShipmentUpdate = (props: IShipmentUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { shipmentEntity, shoppingOrders, users, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/shipment');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getShoppingOrders();
    props.getUsers();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...shipmentEntity,
        ...values,
        order: shoppingOrders.find(it => it.id.toString() === values.orderId.toString()),
        shippedBy: users.find(it => it.id.toString() === values.shippedById.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="mySimpleShopApp.shipment.home.createOrEditLabel" data-cy="ShipmentCreateUpdateHeading">
            <Translate contentKey="mySimpleShopApp.shipment.home.createOrEditLabel">Create or edit a Shipment</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : shipmentEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="shipment-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="shipment-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="shippedAtLabel" for="shipment-shippedAt">
                  <Translate contentKey="mySimpleShopApp.shipment.shippedAt">Shipped At</Translate>
                </Label>
                <AvField
                  id="shipment-shippedAt"
                  data-cy="shippedAt"
                  type="date"
                  className="form-control"
                  name="shippedAt"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label for="shipment-order">
                  <Translate contentKey="mySimpleShopApp.shipment.order">Order</Translate>
                </Label>
                <AvInput id="shipment-order" data-cy="order" type="select" className="form-control" name="orderId" required>
                  <option value="" key="0" />
                  {shoppingOrders
                    ? shoppingOrders.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.name}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <AvGroup>
                <Label for="shipment-shippedBy">
                  <Translate contentKey="mySimpleShopApp.shipment.shippedBy">Shipped By</Translate>
                </Label>
                <AvInput id="shipment-shippedBy" data-cy="shippedBy" type="select" className="form-control" name="shippedById" required>
                  <option value="" key="0" />
                  {users
                    ? users.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.login}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/shipment" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  shoppingOrders: storeState.shoppingOrder.entities,
  users: storeState.userManagement.users,
  shipmentEntity: storeState.shipment.entity,
  loading: storeState.shipment.loading,
  updating: storeState.shipment.updating,
  updateSuccess: storeState.shipment.updateSuccess,
});

const mapDispatchToProps = {
  getShoppingOrders,
  getUsers,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ShipmentUpdate);

// src/main/webapp/app/entities/shipment/shipment-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { IShipment, Shipment } from 'app/shared/model/shipment.model';
import { ShipmentService } from './shipment.service';
import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { ShoppingOrderService } from 'app/entities/shopping-order';
import { IUser, UserService } from 'app/core';

@Component({
  selector: 'bpf-shipment-update',
  templateUrl: './shipment-update.component.html'
})
export class ShipmentUpdateComponent implements OnInit {
  isSaving: boolean;

  orders: IShoppingOrder[];

  users: IUser[];
  shippedAtDp: any;

  editForm = this.fb.group({
    id: [],
    shippedAt: [null, [Validators.required]],
    orderId: [null, Validators.required],
    shippedById: [null, Validators.required]
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected shipmentService: ShipmentService,
    protected shoppingOrderService: ShoppingOrderService,
    protected userService: UserService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ shipment }) => {
      this.updateForm(shipment);
    });
    this.shoppingOrderService
      .query({ filter: 'shipment-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IShoppingOrder[]>) => mayBeOk.ok),
        map((response: HttpResponse<IShoppingOrder[]>) => response.body)
      )
      .subscribe(
        (res: IShoppingOrder[]) => {
          if (!!this.editForm.get('orderId').value) {
            this.orders = res;
          } else {
            this.shoppingOrderService
              .find(this.editForm.get('orderId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IShoppingOrder>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IShoppingOrder>) => subResponse.body)
              )
              .subscribe(
                (subRes: IShoppingOrder) => (this.orders = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.userService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IUser[]>) => mayBeOk.ok),
        map((response: HttpResponse<IUser[]>) => response.body)
      )
      .subscribe((res: IUser[]) => (this.users = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(shipment: IShipment) {
    this.editForm.patchValue({
      id: shipment.id,
      shippedAt: shipment.shippedAt,
      orderId: shipment.orderId,
      shippedById: shipment.shippedById
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const shipment = this.createFromForm();
    if (shipment.id !== undefined) {
      this.subscribeToSaveResponse(this.shipmentService.update(shipment));
    } else {
      this.subscribeToSaveResponse(this.shipmentService.create(shipment));
    }
  }

  private createFromForm(): IShipment {
    return {
      ...new Shipment(),
      id: this.editForm.get(['id']).value,
      shippedAt: this.editForm.get(['shippedAt']).value,
      orderId: this.editForm.get(['orderId']).value,
      shippedById: this.editForm.get(['shippedById']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IShipment>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackShoppingOrderById(index: number, item: IShoppingOrder) {
    return item.id;
  }

  trackUserById(index: number, item: IUser) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="bpf-shipment-heading" jhiTranslate="mySimpleShopApp.shipment.home.createOrEditLabel">Create or edit a Shipment</h2>
            <div>
                <bpf-alert-error></bpf-alert-error>
                <div class="form-group" [hidden]="!shipment.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shipment.shippedAt" for="field_shippedAt">Shipped At</label>
                    <div class="d-flex">
                        <input id="field_shippedAt" type="datetime-local" class="form-control" name="shippedAt" formControlName="shippedAt" placeholder="YYYY-MM-DD HH:mm"/>
                    </div>
                    <div *ngIf="editForm.get('shippedAt').invalid && (editForm.get('shippedAt').dirty || editForm.get('shippedAt').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('shippedAt').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('shippedAt').errors?.ZonedDateTimelocal" jhiTranslate="entity.validation.ZonedDateTimelocal">
                            This field should be a date and time.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shipment.order" for="field_order">Order</label>
                    <select class="form-control" id="field_order" name="order" formControlName="orderId">
                        <option *ngIf="!editForm.get('orderId').value" [ngValue]="null" selected></option>
                        <option [ngValue]="shoppingOrderOption.id" *ngFor="let shoppingOrderOption of orders; trackBy: trackShoppingOrderById">{{shoppingOrderOption.name}}</option>
                    </select>
                </div>
                <div *ngIf="editForm.get('orderId').invalid && (editForm.get('orderId').dirty || editForm.get('orderId').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('orderId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shipment.shippedBy" for="field_shippedBy">Shipped By</label>
                    <select class="form-control" id="field_shippedBy" name="shippedBy" formControlName="shippedById">
                        <option *ngIf="!editForm.get('shippedById').value" [ngValue]="null" selected></option>
                        <option [ngValue]="userOption.id" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
                <div *ngIf="editForm.get('shippedById').invalid && (editForm.get('shippedById').dirty || editForm.get('shippedById').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('shippedById').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
