// src/main/webapp/app/entities/product-order/product-order-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IUser } from 'app/shared/model/user.model';
import { getUsers } from 'app/modules/administration/user-management/user-management.reducer';
import { IProduct } from 'app/shared/model/product.model';
import { getEntities as getProducts } from 'app/entities/product/product.reducer';
import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { getEntities as getShoppingOrders } from 'app/entities/shopping-order/shopping-order.reducer';
import { getEntity, updateEntity, createEntity, reset } from './product-order.reducer';
import { IProductOrder } from 'app/shared/model/product-order.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IProductOrderUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ProductOrderUpdate = (props: IProductOrderUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { productOrderEntity, users, products, shoppingOrders, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/product-order');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getUsers();
    props.getProducts();
    props.getShoppingOrders();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...productOrderEntity,
        ...values,
        buyer: users.find(it => it.id.toString() === values.buyerId.toString()),
        product: products.find(it => it.id.toString() === values.productId.toString()),
        overallOrder: shoppingOrders.find(it => it.id.toString() === values.overallOrderId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="mySimpleShopApp.productOrder.home.createOrEditLabel" data-cy="ProductOrderCreateUpdateHeading">
            <Translate contentKey="mySimpleShopApp.productOrder.home.createOrEditLabel">Create or edit a ProductOrder</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : productOrderEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="product-order-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="product-order-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="amountLabel" for="product-order-amount">
                  <Translate contentKey="mySimpleShopApp.productOrder.amount">Amount</Translate>
                </Label>
                <AvField
                  id="product-order-amount"
                  data-cy="amount"
                  type="string"
                  className="form-control"
                  name="amount"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    min: { value: 0, errorMessage: translate('entity.validation.min', { min: 0 }) },
                    max: { value: 5, errorMessage: translate('entity.validation.max', { max: 5 }) },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label for="product-order-buyer">
                  <Translate contentKey="mySimpleShopApp.productOrder.buyer">Buyer</Translate>
                </Label>
                <AvInput id="product-order-buyer" data-cy="buyer" type="select" className="form-control" name="buyerId" required>
                  <option value="" key="0" />
                  {users
                    ? users.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.login}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <AvGroup>
                <Label for="product-order-product">
                  <Translate contentKey="mySimpleShopApp.productOrder.product">Product</Translate>
                </Label>
                <AvInput id="product-order-product" data-cy="product" type="select" className="form-control" name="productId" required>
                  <option value="" key="0" />
                  {products
                    ? products.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.name}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <AvGroup>
                <Label for="product-order-overallOrder">
                  <Translate contentKey="mySimpleShopApp.productOrder.overallOrder">Overall Order</Translate>
                </Label>
                <AvInput
                  id="product-order-overallOrder"
                  data-cy="overallOrder"
                  type="select"
                  className="form-control"
                  name="overallOrderId"
                  required
                >
                  <option value="" key="0" />
                  {shoppingOrders
                    ? shoppingOrders.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.name}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/product-order" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  users: storeState.userManagement.users,
  products: storeState.product.entities,
  shoppingOrders: storeState.shoppingOrder.entities,
  productOrderEntity: storeState.productOrder.entity,
  loading: storeState.productOrder.loading,
  updating: storeState.productOrder.updating,
  updateSuccess: storeState.productOrder.updateSuccess,
});

const mapDispatchToProps = {
  getUsers,
  getProducts,
  getShoppingOrders,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ProductOrderUpdate);

// src/main/webapp/app/entities/product-order/product-order-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IProductOrder, ProductOrder } from 'app/shared/model/product-order.model';
import { ProductOrderService } from './product-order.service';
import { IUser, UserService } from 'app/core';
import { IProduct } from 'app/shared/model/product.model';
import { ProductService } from 'app/entities/product';
import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { ShoppingOrderService } from 'app/entities/shopping-order';

@Component({
  selector: 'bpf-product-order-update',
  templateUrl: './product-order-update.component.html'
})
export class ProductOrderUpdateComponent implements OnInit {
  isSaving: boolean;

  users: IUser[];

  products: IProduct[];

  shoppingorders: IShoppingOrder[];

  editForm = this.fb.group({
    id: [],
    amount: [null, [Validators.required, Validators.min(0), Validators.max(5)]],
    buyerId: [null, Validators.required],
    productId: [null, Validators.required],
    overallOrderId: [null, Validators.required]
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected productOrderService: ProductOrderService,
    protected userService: UserService,
    protected productService: ProductService,
    protected shoppingOrderService: ShoppingOrderService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ productOrder }) => {
      this.updateForm(productOrder);
    });
    this.userService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IUser[]>) => mayBeOk.ok),
        map((response: HttpResponse<IUser[]>) => response.body)
      )
      .subscribe((res: IUser[]) => (this.users = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.productService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProduct[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProduct[]>) => response.body)
      )
      .subscribe((res: IProduct[]) => (this.products = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.shoppingOrderService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IShoppingOrder[]>) => mayBeOk.ok),
        map((response: HttpResponse<IShoppingOrder[]>) => response.body)
      )
      .subscribe((res: IShoppingOrder[]) => (this.shoppingorders = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(productOrder: IProductOrder) {
    this.editForm.patchValue({
      id: productOrder.id,
      amount: productOrder.amount,
      buyerId: productOrder.buyerId,
      productId: productOrder.productId,
      overallOrderId: productOrder.overallOrderId
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const productOrder = this.createFromForm();
    if (productOrder.id !== undefined) {
      this.subscribeToSaveResponse(this.productOrderService.update(productOrder));
    } else {
      this.subscribeToSaveResponse(this.productOrderService.create(productOrder));
    }
  }

  private createFromForm(): IProductOrder {
    return {
      ...new ProductOrder(),
      id: this.editForm.get(['id']).value,
      amount: this.editForm.get(['amount']).value,
      buyerId: this.editForm.get(['buyerId']).value,
      productId: this.editForm.get(['productId']).value,
      overallOrderId: this.editForm.get(['overallOrderId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProductOrder>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackUserById(index: number, item: IUser) {
    return item.id;
  }

  trackProductById(index: number, item: IProduct) {
    return item.id;
  }

  trackShoppingOrderById(index: number, item: IShoppingOrder) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="bpf-product-order-heading" jhiTranslate="mySimpleShopApp.productOrder.home.createOrEditLabel">Create or edit a Product Order</h2>
            <div>
                <bpf-alert-error></bpf-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.productOrder.amount" for="field_amount">Amount</label>
                    <input type="number" class="form-control" name="amount" id="field_amount"
                           formControlName="amount"/>
                    <div *ngIf="editForm.get('amount').invalid && (editForm.get('amount').dirty || editForm.get('amount').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('amount').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('amount').errors.min" jhiTranslate="entity.validation.min" [translateValues]="{ min: 0 }">
                            This field should be at least 0.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('amount').errors.max" jhiTranslate="entity.validation.max" [translateValues]="{ max: 5 }">
                            This field cannot be more than 5.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('amount')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.productOrder.buyer" for="field_buyer">Buyer</label>
                    <select class="form-control" id="field_buyer" name="buyer" formControlName="buyerId">
                        <option *ngIf="!editForm.get('buyerId').value" [ngValue]="null" selected></option>
                        <option [ngValue]="userOption.id" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
                <div *ngIf="editForm.get('buyerId').invalid && (editForm.get('buyerId').dirty || editForm.get('buyerId').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('buyerId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.productOrder.product" for="field_product">Product</label>
                    <select class="form-control" id="field_product" name="product" formControlName="productId">
                        <option *ngIf="!editForm.get('productId').value" [ngValue]="null" selected></option>
                        <option [ngValue]="productOption.id" *ngFor="let productOption of products; trackBy: trackProductById">{{productOption.name}}</option>
                    </select>
                </div>
                <div *ngIf="editForm.get('productId').invalid && (editForm.get('productId').dirty || editForm.get('productId').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('productId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.productOrder.overallOrder" for="field_overallOrder">Overall Order</label>
                    <select class="form-control" id="field_overallOrder" name="overallOrder" formControlName="overallOrderId">
                        <option *ngIf="!editForm.get('overallOrderId').value" [ngValue]="null" selected></option>
                        <option [ngValue]="shoppingOrderOption.id" *ngFor="let shoppingOrderOption of shoppingorders; trackBy: trackShoppingOrderById">{{shoppingOrderOption.name}}</option>
                    </select>
                </div>
                <div *ngIf="editForm.get('overallOrderId').invalid && (editForm.get('overallOrderId').dirty || editForm.get('overallOrderId').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('overallOrderId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
