// src/main/webapp/app/entities/product-order/product-order.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './product-order.reducer';
import { IProductOrder } from 'app/shared/model/product-order.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ProductOrder = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const productOrderList = useAppSelector(state => state.productOrder.entities);
  const loading = useAppSelector(state => state.productOrder.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="product-order-heading" data-cy="ProductOrderHeading">
        <Translate contentKey="mySimpleShopApp.productOrder.home.title">Product Orders</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="mySimpleShopApp.productOrder.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="mySimpleShopApp.productOrder.home.createLabel">Create new Product Order</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {productOrderList && productOrderList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="mySimpleShopApp.productOrder.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.productOrder.amount">Amount</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.productOrder.buyer">Buyer</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.productOrder.product">Product</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.productOrder.overallOrder">Overall Order</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {productOrderList.map((productOrder, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${productOrder.id}`} color="link" size="sm">
                      {productOrder.id}
                    </Button>
                  </td>
                  <td>{productOrder.amount}</td>
                  <td>{productOrder.buyer ? productOrder.buyer.login : ''}</td>
                  <td>{productOrder.product ? <Link to={`product/${productOrder.product.id}`}>{productOrder.product.name}</Link> : ''}</td>
                  <td>
                    {productOrder.overallOrder ? (
                      <Link to={`shopping-order/${productOrder.overallOrder.id}`}>{productOrder.overallOrder.name}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${productOrder.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${productOrder.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${productOrder.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="mySimpleShopApp.productOrder.home.notFound">No Product Orders found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default ProductOrder;

// src/main/webapp/app/entities/product-order/product-order.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IProductOrder } from 'app/shared/model/product-order.model';
import { ProductOrderService } from './product-order.service';
import { ProductOrderDeleteDialogComponent } from './product-order-delete-dialog.component';

@Component({
  selector: 'bpf-product-order',
  templateUrl: './product-order.component.html',
})
export class ProductOrderComponent implements OnInit, OnDestroy {
  productOrders?: IProductOrder[];
  eventSubscriber?: Subscription;

  constructor(
    protected productOrderService: ProductOrderService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.productOrderService.query().subscribe((res: HttpResponse<IProductOrder[]>) => (this.productOrders = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInProductOrders();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IProductOrder): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInProductOrders(): void {
    this.eventSubscriber = this.eventManager.subscribe('productOrderListModification', () => this.loadAll());
  }

  delete(productOrder: IProductOrder): void {
    const modalRef = this.modalService.open(ProductOrderDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.productOrder = productOrder;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="mySimpleShopApp.productOrder.home.title">Product Orders</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-product-order" [routerLink]="['/product-order/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="mySimpleShopApp.productOrder.home.createLabel">
            Create a new Product Order
            </span>
        </button>
    </h2>

    <bpf-alert-error></bpf-alert-error>

    <bpf-alert></bpf-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="productOrders?.length === 0">
        <span jhiTranslate="mySimpleShopApp.productOrder.home.notFound">No productOrders found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="productOrders && productOrders.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.productOrder.amount">Amount</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.productOrder.buyer">Buyer</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.productOrder.product">Product</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.productOrder.overallOrder">Overall Order</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let productOrder of productOrders ;trackBy: trackId">
                    <td><a [routerLink]="['/product-order', productOrder.id, 'view']">{{ productOrder.id }}</a></td>
                    <td>{{ productOrder.amount }}</td>
                    <td>
                        {{ productOrder.buyerLogin }}
                    </td>
                    <td>
                        <div *ngIf="productOrder.productId">
                            <a [routerLink]="['/product', productOrder.productId , 'view']" >{{ productOrder.productName }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="productOrder.overallOrderId">
                            <a [routerLink]="['/shopping-order', productOrder.overallOrderId , 'view']" >{{ productOrder.overallOrderName }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/product-order', productOrder.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/product-order', productOrder.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(productOrder)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
