// src/main/webapp/app/entities/product-order/product-order-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './product-order.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ProductOrderDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const productOrderEntity = useAppSelector(state => state.productOrder.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="productOrderDetailsHeading">
          <Translate contentKey="mySimpleShopApp.productOrder.detail.title">ProductOrder</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{productOrderEntity.id}</dd>
          <dt>
            <span id="amount">
              <Translate contentKey="mySimpleShopApp.productOrder.amount">Amount</Translate>
            </span>
          </dt>
          <dd>{productOrderEntity.amount}</dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.productOrder.buyer">Buyer</Translate>
          </dt>
          <dd>{productOrderEntity.buyer ? productOrderEntity.buyer.login : ''}</dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.productOrder.product">Product</Translate>
          </dt>
          <dd>{productOrderEntity.product ? productOrderEntity.product.name : ''}</dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.productOrder.overallOrder">Overall Order</Translate>
          </dt>
          <dd>{productOrderEntity.overallOrder ? productOrderEntity.overallOrder.name : ''}</dd>
        </dl>
        <Button tag={Link} to="/product-order" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/product-order/${productOrderEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ProductOrderDetail;

// src/main/webapp/app/entities/product-order/product-order-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IProductOrder } from 'app/shared/model/product-order.model';

@Component({
  selector: 'bpf-product-order-detail',
  templateUrl: './product-order-detail.component.html',
})
export class ProductOrderDetailComponent implements OnInit {
  productOrder: IProductOrder | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ productOrder }) => (this.productOrder = productOrder));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="productOrder">
            <h2><span jhiTranslate="mySimpleShopApp.productOrder.detail.title">Product Order</span> {{ productOrder.id }}</h2>

            <hr>

            <bpf-alert-error></bpf-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="mySimpleShopApp.productOrder.amount">Amount</span></dt>
                <dd>
                    <span>{{ productOrder.amount }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.productOrder.buyer">Buyer</span></dt>
                <dd>
                    {{ productOrder.buyerLogin }}
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.productOrder.product">Product</span></dt>
                <dd>
                    <div *ngIf="productOrder.productId">
                        <a [routerLink]="['/product', productOrder.productId, 'view']">{{ productOrder.productName }}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.productOrder.overallOrder">Overall Order</span></dt>
                <dd>
                    <div *ngIf="productOrder.overallOrderId">
                        <a [routerLink]="['/shopping-order', productOrder.overallOrderId, 'view']">{{ productOrder.overallOrderName }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/product-order', productOrder.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
