// src/main/webapp/app/entities/shopping-order/shopping-order-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './shopping-order.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ShoppingOrderDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const shoppingOrderEntity = useAppSelector(state => state.shoppingOrder.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="shoppingOrderDetailsHeading">
          <Translate contentKey="mySimpleShopApp.shoppingOrder.detail.title">ShoppingOrder</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{shoppingOrderEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="mySimpleShopApp.shoppingOrder.name">Name</Translate>
            </span>
          </dt>
          <dd>{shoppingOrderEntity.name}</dd>
          <dt>
            <span id="totalAmount">
              <Translate contentKey="mySimpleShopApp.shoppingOrder.totalAmount">Total Amount</Translate>
            </span>
          </dt>
          <dd>{shoppingOrderEntity.totalAmount}</dd>
          <dt>
            <span id="ordered">
              <Translate contentKey="mySimpleShopApp.shoppingOrder.ordered">Ordered</Translate>
            </span>
          </dt>
          <dd>
            {shoppingOrderEntity.ordered ? (
              <TextFormat value={shoppingOrderEntity.ordered} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <Translate contentKey="mySimpleShopApp.shoppingOrder.buyer">Buyer</Translate>
          </dt>
          <dd>{shoppingOrderEntity.buyer ? shoppingOrderEntity.buyer.login : ''}</dd>
        </dl>
        <Button tag={Link} to="/shopping-order" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/shopping-order/${shoppingOrderEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ShoppingOrderDetail;

// src/main/webapp/app/entities/shopping-order/shopping-order-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IShoppingOrder } from 'app/shared/model/shopping-order.model';

@Component({
  selector: 'bpf-shopping-order-detail',
  templateUrl: './shopping-order-detail.component.html'
})
export class ShoppingOrderDetailComponent implements OnInit {
  shoppingOrder: IShoppingOrder;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ shoppingOrder }) => {
      this.shoppingOrder = shoppingOrder;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="shoppingOrder">
            <h2><span jhiTranslate="mySimpleShopApp.shoppingOrder.detail.title">Shopping Order</span> {{ shoppingOrder.id }}</h2>

            <hr>

            <bpf-alert-error></bpf-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="mySimpleShopApp.shoppingOrder.name">Name</span></dt>
                <dd>
                    <span>{{ shoppingOrder.name }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.shoppingOrder.totalAmount">Total Amount</span></dt>
                <dd>
                    <span>{{ shoppingOrder.totalAmount }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.shoppingOrder.ordered">Ordered</span></dt>
                <dd>
                    <span>{{ shoppingOrder.ordered }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.shoppingOrder.buyer">Buyer</span></dt>
                <dd>
                    {{ shoppingOrder.buyerLogin }}
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/shopping-order', shoppingOrder.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
