// src/main/webapp/app/entities/shopping-order/shopping-order-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IUser } from 'app/shared/model/user.model';
import { getUsers } from 'app/modules/administration/user-management/user-management.reducer';
import { IShipment } from 'app/shared/model/shipment.model';
import { getEntities as getShipments } from 'app/entities/shipment/shipment.reducer';
import { getEntity, updateEntity, createEntity, reset } from './shopping-order.reducer';
import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IShoppingOrderUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ShoppingOrderUpdate = (props: IShoppingOrderUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { shoppingOrderEntity, users, shipments, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/shopping-order');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getUsers();
    props.getShipments();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...shoppingOrderEntity,
        ...values,
        buyer: users.find(it => it.id.toString() === values.buyerId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="mySimpleShopApp.shoppingOrder.home.createOrEditLabel" data-cy="ShoppingOrderCreateUpdateHeading">
            <Translate contentKey="mySimpleShopApp.shoppingOrder.home.createOrEditLabel">Create or edit a ShoppingOrder</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : shoppingOrderEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="shopping-order-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="shopping-order-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nameLabel" for="shopping-order-name">
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.name">Name</Translate>
                </Label>
                <AvField
                  id="shopping-order-name"
                  data-cy="name"
                  type="text"
                  name="name"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                    maxLength: { value: 90, errorMessage: translate('entity.validation.maxlength', { max: 90 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="totalAmountLabel" for="shopping-order-totalAmount">
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.totalAmount">Total Amount</Translate>
                </Label>
                <AvField
                  id="shopping-order-totalAmount"
                  data-cy="totalAmount"
                  type="string"
                  className="form-control"
                  name="totalAmount"
                  validate={{
                    min: { value: 0, errorMessage: translate('entity.validation.min', { min: 0 }) },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="orderedLabel" for="shopping-order-ordered">
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.ordered">Ordered</Translate>
                </Label>
                <AvField id="shopping-order-ordered" data-cy="ordered" type="date" className="form-control" name="ordered" />
              </AvGroup>
              <AvGroup>
                <Label for="shopping-order-buyer">
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.buyer">Buyer</Translate>
                </Label>
                <AvInput id="shopping-order-buyer" data-cy="buyer" type="select" className="form-control" name="buyerId" required>
                  <option value="" key="0" />
                  {users
                    ? users.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.login}
                        </option>
                      ))
                    : null}
                </AvInput>
                <AvFeedback>
                  <Translate contentKey="entity.validation.required">This field is required.</Translate>
                </AvFeedback>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/shopping-order" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  users: storeState.userManagement.users,
  shipments: storeState.shipment.entities,
  shoppingOrderEntity: storeState.shoppingOrder.entity,
  loading: storeState.shoppingOrder.loading,
  updating: storeState.shoppingOrder.updating,
  updateSuccess: storeState.shoppingOrder.updateSuccess,
});

const mapDispatchToProps = {
  getUsers,
  getShipments,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ShoppingOrderUpdate);

// src/main/webapp/app/entities/shopping-order/shopping-order-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { IShoppingOrder, ShoppingOrder } from 'app/shared/model/shopping-order.model';
import { ShoppingOrderService } from './shopping-order.service';
import { IUser, UserService } from 'app/core';
import { IShipment } from 'app/shared/model/shipment.model';
import { ShipmentService } from 'app/entities/shipment';

@Component({
  selector: 'bpf-shopping-order-update',
  templateUrl: './shopping-order-update.component.html'
})
export class ShoppingOrderUpdateComponent implements OnInit {
  isSaving: boolean;

  users: IUser[];

  shipments: IShipment[];
  orderedDp: any;

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required, Validators.minLength(2), Validators.maxLength(90)]],
    totalAmount: [null, [Validators.min(0)]],
    ordered: [],
    buyerId: [null, Validators.required]
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected shoppingOrderService: ShoppingOrderService,
    protected userService: UserService,
    protected shipmentService: ShipmentService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ shoppingOrder }) => {
      this.updateForm(shoppingOrder);
    });
    this.userService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IUser[]>) => mayBeOk.ok),
        map((response: HttpResponse<IUser[]>) => response.body)
      )
      .subscribe((res: IUser[]) => (this.users = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.shipmentService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IShipment[]>) => mayBeOk.ok),
        map((response: HttpResponse<IShipment[]>) => response.body)
      )
      .subscribe((res: IShipment[]) => (this.shipments = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(shoppingOrder: IShoppingOrder) {
    this.editForm.patchValue({
      id: shoppingOrder.id,
      name: shoppingOrder.name,
      totalAmount: shoppingOrder.totalAmount,
      ordered: shoppingOrder.ordered,
      buyerId: shoppingOrder.buyerId
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const shoppingOrder = this.createFromForm();
    if (shoppingOrder.id !== undefined) {
      this.subscribeToSaveResponse(this.shoppingOrderService.update(shoppingOrder));
    } else {
      this.subscribeToSaveResponse(this.shoppingOrderService.create(shoppingOrder));
    }
  }

  private createFromForm(): IShoppingOrder {
    return {
      ...new ShoppingOrder(),
      id: this.editForm.get(['id']).value,
      name: this.editForm.get(['name']).value,
      totalAmount: this.editForm.get(['totalAmount']).value,
      ordered: this.editForm.get(['ordered']).value,
      buyerId: this.editForm.get(['buyerId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IShoppingOrder>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackUserById(index: number, item: IUser) {
    return item.id;
  }

  trackShipmentById(index: number, item: IShipment) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="bpf-shopping-order-heading" jhiTranslate="mySimpleShopApp.shoppingOrder.home.createOrEditLabel">Create or edit a Shopping Order</h2>
            <div>
                <bpf-alert-error></bpf-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shoppingOrder.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                    <div *ngIf="editForm.get('name').invalid && (editForm.get('name').dirty || editForm.get('name').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.minlength" jhiTranslate="entity.validation.minlength" [translateValues]="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.maxlength" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: 90 }">
                        This field cannot be longer than 90 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shoppingOrder.totalAmount" for="field_totalAmount">Total Amount</label>
                    <input type="number" class="form-control" name="totalAmount" id="field_totalAmount"
                           formControlName="totalAmount"/>
                    <div *ngIf="editForm.get('totalAmount').invalid && (editForm.get('totalAmount').dirty || editForm.get('totalAmount').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('totalAmount').errors.min" jhiTranslate="entity.validation.min" [translateValues]="{ min: 0 }">
                            This field should be at least 0.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('totalAmount')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shoppingOrder.ordered" for="field_ordered">Ordered</label>
                    <div class="input-group">
                        <input id="field_ordered" type="text" class="form-control" name="ordered" ngbDatepicker  #orderedDp="ngbDatepicker" formControlName="ordered"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="orderedDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.shoppingOrder.buyer" for="field_buyer">Buyer</label>
                    <select class="form-control" id="field_buyer" name="buyer" formControlName="buyerId">
                        <option *ngIf="!editForm.get('buyerId').value" [ngValue]="null" selected></option>
                        <option [ngValue]="userOption.id" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
                <div *ngIf="editForm.get('buyerId').invalid && (editForm.get('buyerId').dirty || editForm.get('buyerId').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('buyerId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
