// src/main/webapp/app/entities/shopping-order/shopping-order.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './shopping-order.reducer';
import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ShoppingOrder = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const shoppingOrderList = useAppSelector(state => state.shoppingOrder.entities);
  const loading = useAppSelector(state => state.shoppingOrder.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="shopping-order-heading" data-cy="ShoppingOrderHeading">
        <Translate contentKey="mySimpleShopApp.shoppingOrder.home.title">Shopping Orders</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="mySimpleShopApp.shoppingOrder.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="mySimpleShopApp.shoppingOrder.home.createLabel">Create new Shopping Order</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {shoppingOrderList && shoppingOrderList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.totalAmount">Total Amount</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.ordered">Ordered</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.shoppingOrder.buyer">Buyer</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {shoppingOrderList.map((shoppingOrder, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${shoppingOrder.id}`} color="link" size="sm">
                      {shoppingOrder.id}
                    </Button>
                  </td>
                  <td>{shoppingOrder.name}</td>
                  <td>{shoppingOrder.totalAmount}</td>
                  <td>
                    {shoppingOrder.ordered ? <TextFormat type="date" value={shoppingOrder.ordered} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{shoppingOrder.buyer ? shoppingOrder.buyer.login : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${shoppingOrder.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${shoppingOrder.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${shoppingOrder.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="mySimpleShopApp.shoppingOrder.home.notFound">No Shopping Orders found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default ShoppingOrder;

// src/main/webapp/app/entities/shopping-order/shopping-order.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IShoppingOrder } from 'app/shared/model/shopping-order.model';
import { AccountService } from 'app/core';
import { ShoppingOrderService } from './shopping-order.service';

@Component({
  selector: 'bpf-shopping-order',
  templateUrl: './shopping-order.component.html'
})
export class ShoppingOrderComponent implements OnInit, OnDestroy {
  shoppingOrders: IShoppingOrder[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected shoppingOrderService: ShoppingOrderService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.shoppingOrderService
      .query()
      .pipe(
        filter((res: HttpResponse<IShoppingOrder[]>) => res.ok),
        map((res: HttpResponse<IShoppingOrder[]>) => res.body)
      )
      .subscribe(
        (res: IShoppingOrder[]) => {
          this.shoppingOrders = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInShoppingOrders();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IShoppingOrder) {
    return item.id;
  }

  registerChangeInShoppingOrders() {
    this.eventSubscriber = this.eventManager.subscribe('shoppingOrderListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="mySimpleShopApp.shoppingOrder.home.title">Shopping Orders</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-shopping-order" [routerLink]="['/shopping-order/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="mySimpleShopApp.shoppingOrder.home.createLabel">
            Create a new Shopping Order
            </span>
        </button>
    </h2>

    <bpf-alert-error></bpf-alert-error>

    <bpf-alert></bpf-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="shoppingOrders?.length === 0">
        <span jhiTranslate="mySimpleShopApp.shoppingOrder.home.notFound">No shoppingOrders found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="shoppingOrders && shoppingOrders.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shoppingOrder.name">Name</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shoppingOrder.totalAmount">Total Amount</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shoppingOrder.ordered">Ordered</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.shoppingOrder.buyer">Buyer</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let shoppingOrder of shoppingOrders ;trackBy: trackId">
                    <td><a [routerLink]="['/shopping-order', shoppingOrder.id, 'view']">{{ shoppingOrder.id }}</a></td>
                    <td>{{ shoppingOrder.name }}</td>
                    <td>{{ shoppingOrder.totalAmount }}</td>
                    <td>{{ shoppingOrder.ordered | date:'mediumDate' }}</td>
                    <td>
                        {{ shoppingOrder.buyerLogin }}
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/shopping-order', shoppingOrder.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/shopping-order', shoppingOrder.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(shoppingOrder)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
