// src/main/webapp/app/entities/product/product-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './product.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const ProductDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const productEntity = useAppSelector(state => state.product.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="productDetailsHeading">
          <Translate contentKey="mySimpleShopApp.product.detail.title">Product</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{productEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="mySimpleShopApp.product.name">Name</Translate>
            </span>
          </dt>
          <dd>{productEntity.name}</dd>
          <dt>
            <span id="price">
              <Translate contentKey="mySimpleShopApp.product.price">Price</Translate>
            </span>
          </dt>
          <dd>{productEntity.price}</dd>
          <dt>
            <span id="description">
              <Translate contentKey="mySimpleShopApp.product.description">Description</Translate>
            </span>
          </dt>
          <dd>{productEntity.description}</dd>
          <dt>
            <span id="picture">
              <Translate contentKey="mySimpleShopApp.product.picture">Picture</Translate>
            </span>
          </dt>
          <dd>
            {productEntity.picture ? (
              <div>
                {productEntity.pictureContentType ? (
                  <a onClick={openFile(productEntity.pictureContentType, productEntity.picture)}>
                    <img src={`data:${productEntity.pictureContentType};base64,${productEntity.picture}`} style={{ maxHeight: '30px' }} />
                  </a>
                ) : null}
                <span>
                  {productEntity.pictureContentType}, {byteSize(productEntity.picture)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="specification">
              <Translate contentKey="mySimpleShopApp.product.specification">Specification</Translate>
            </span>
          </dt>
          <dd>
            {productEntity.specification ? (
              <div>
                {productEntity.specificationContentType ? (
                  <a onClick={openFile(productEntity.specificationContentType, productEntity.specification)}>
                    <Translate contentKey="entity.action.open">Open</Translate>&nbsp;
                  </a>
                ) : null}
                <span>
                  {productEntity.specificationContentType}, {byteSize(productEntity.specification)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="category">
              <Translate contentKey="mySimpleShopApp.product.category">Category</Translate>
            </span>
          </dt>
          <dd>{productEntity.category}</dd>
          <dt>
            <span id="inventory">
              <Translate contentKey="mySimpleShopApp.product.inventory">Inventory</Translate>
            </span>
          </dt>
          <dd>{productEntity.inventory}</dd>
        </dl>
        <Button tag={Link} to="/product" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/product/${productEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ProductDetail;

// src/main/webapp/app/entities/product/product-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { JhiDataUtils } from 'ng-jhipster';

import { IProduct } from 'app/shared/model/product.model';

@Component({
  selector: 'bpf-product-detail',
  templateUrl: './product-detail.component.html'
})
export class ProductDetailComponent implements OnInit {
  product: IProduct;

  constructor(protected dataUtils: JhiDataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ product }) => {
      this.product = product;
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }
  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="product">
            <h2><span jhiTranslate="mySimpleShopApp.product.detail.title">Product</span> {{ product.id }}</h2>

            <hr>

            <bpf-alert-error></bpf-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="mySimpleShopApp.product.name">Name</span></dt>
                <dd>
                    <span>{{ product.name }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.product.price">Price</span></dt>
                <dd>
                    <span>{{ product.price }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.product.description">Description</span></dt>
                <dd>
                    <span>{{ product.description }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.product.picture">Picture</span></dt>
                <dd>
                    <div *ngIf="product.picture">
                        <a (click)="openFile(product.pictureContentType, product.picture)">
                            <img [src]="'data:' + product.pictureContentType + ';base64,' + product.picture" style="max-width: 100%;" alt="product image"/>
                        </a>
                        {{ product.pictureContentType }}, {{ byteSize(product.picture) }}
                    </div>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.product.specification">Specification</span></dt>
                <dd>
                    <div *ngIf="product.specification">
                        <a (click)="openFile(product.specificationContentType, product.specification)" jhiTranslate="entity.action.open">open</a>
                        {{ product.specificationContentType }}, {{ byteSize(product.specification) }}
                    </div>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.product.category">Category</span></dt>
                <dd>
                    <span jhiTranslate="{{ 'mySimpleShopApp.ProductCategory.' + product.category }}">{{ product.category }}</span>
                </dd>
                <dt><span jhiTranslate="mySimpleShopApp.product.inventory">Inventory</span></dt>
                <dd>
                    <span>{{ product.inventory }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/product', product.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
