// src/main/webapp/app/entities/product/product.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager, JhiDataUtils } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IProduct } from 'app/shared/model/product.model';
import { ProductService } from './product.service';
import { ProductDeleteDialogComponent } from './product-delete-dialog.component';

@Component({
  selector: 'bpf-product',
  templateUrl: './product.component.html',
})
export class ProductComponent implements OnInit, OnDestroy {
  products?: IProduct[];
  eventSubscriber?: Subscription;

  constructor(
    protected productService: ProductService,
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.productService.query().subscribe((res: HttpResponse<IProduct[]>) => (this.products = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInProducts();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IProduct): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType = '', base64String: string): void {
    return this.dataUtils.openFile(contentType, base64String);
  }

  registerChangeInProducts(): void {
    this.eventSubscriber = this.eventManager.subscribe('productListModification', () => this.loadAll());
  }

  delete(product: IProduct): void {
    const modalRef = this.modalService.open(ProductDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.product = product;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="mySimpleShopApp.product.home.title">Products</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-product" [routerLink]="['/product/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="mySimpleShopApp.product.home.createLabel">
            Create a new Product
            </span>
        </button>
    </h2>

    <bpf-alert-error></bpf-alert-error>

    <bpf-alert></bpf-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="products?.length === 0">
        <span jhiTranslate="mySimpleShopApp.product.home.notFound">No products found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="products && products.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.name">Name</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.price">Price</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.description">Description</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.picture">Picture</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.specification">Specification</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.category">Category</span></th>
                    <th scope="col" ><span jhiTranslate="mySimpleShopApp.product.inventory">Inventory</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let product of products ;trackBy: trackId">
                    <td><a [routerLink]="['/product', product.id, 'view']">{{ product.id }}</a></td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.description }}</td>
                    <td>
                        <a *ngIf="product.picture" (click)="openFile(product.pictureContentType, product.picture)">
                            <img [src]="'data:' + product.pictureContentType + ';base64,' + product.picture" style="max-height: 30px;" alt="product image"/>
                        </a>
                        <span *ngIf="product.picture">{{ product.pictureContentType }}, {{ byteSize(product.picture) }}</span>
                    </td>
                    <td>
                        <a *ngIf="product.specification" (click)="openFile(product.specificationContentType, product.specification)" jhiTranslate="entity.action.open">open</a>
                        <span *ngIf="product.specification">{{ product.specificationContentType }}, {{ byteSize(product.specification) }}</span>
                    </td>
                    <td jhiTranslate="{{ 'mySimpleShopApp.ProductCategory.' + product.category }}">{{ product.category }}</td>
                    <td>{{ product.inventory }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/product', product.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/product', product.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(product)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/product/product.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { openFile, byteSize, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './product.reducer';
import { IProduct } from 'app/shared/model/product.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const Product = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const productList = useAppSelector(state => state.product.entities);
  const loading = useAppSelector(state => state.product.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="product-heading" data-cy="ProductHeading">
        <Translate contentKey="mySimpleShopApp.product.home.title">Products</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="mySimpleShopApp.product.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="mySimpleShopApp.product.home.createLabel">Create new Product</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {productList && productList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.price">Price</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.description">Description</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.picture">Picture</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.specification">Specification</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.category">Category</Translate>
                </th>
                <th>
                  <Translate contentKey="mySimpleShopApp.product.inventory">Inventory</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {productList.map((product, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${product.id}`} color="link" size="sm">
                      {product.id}
                    </Button>
                  </td>
                  <td>{product.name}</td>
                  <td>{product.price}</td>
                  <td>{product.description}</td>
                  <td>
                    {product.picture ? (
                      <div>
                        {product.pictureContentType ? (
                          <a onClick={openFile(product.pictureContentType, product.picture)}>
                            <img src={`data:${product.pictureContentType};base64,${product.picture}`} style={{ maxHeight: '30px' }} />
                            &nbsp;
                          </a>
                        ) : null}
                        <span>
                          {product.pictureContentType}, {byteSize(product.picture)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>
                    {product.specification ? (
                      <div>
                        {product.specificationContentType ? (
                          <a onClick={openFile(product.specificationContentType, product.specification)}>
                            <Translate contentKey="entity.action.open">Open</Translate>
                            &nbsp;
                          </a>
                        ) : null}
                        <span>
                          {product.specificationContentType}, {byteSize(product.specification)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>
                    <Translate contentKey={`mySimpleShopApp.ProductCategory.${product.category}`} />
                  </td>
                  <td>{product.inventory}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${product.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${product.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${product.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="mySimpleShopApp.product.home.notFound">No Products found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Product;
