// src/main/webapp/app/entities/product/product-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { setFileData, openFile, byteSize, Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, setBlob, reset } from './product.reducer';
import { IProduct } from 'app/shared/model/product.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IProductUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ProductUpdate = (props: IProductUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { productEntity, loading, updating } = props;

  const { description, picture, pictureContentType, specification, specificationContentType } = productEntity;

  const handleClose = () => {
    props.history.push('/product');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  const onBlobChange = (isAnImage, name) => event => {
    setFileData(event, (contentType, data) => props.setBlob(name, data, contentType), isAnImage);
  };

  const clearBlob = name => () => {
    props.setBlob(name, undefined, undefined);
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...productEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="mySimpleShopApp.product.home.createOrEditLabel" data-cy="ProductCreateUpdateHeading">
            <Translate contentKey="mySimpleShopApp.product.home.createOrEditLabel">Create or edit a Product</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : productEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="product-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="product-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nameLabel" for="product-name">
                  <Translate contentKey="mySimpleShopApp.product.name">Name</Translate>
                </Label>
                <AvField
                  id="product-name"
                  data-cy="name"
                  type="text"
                  name="name"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    minLength: { value: 2, errorMessage: translate('entity.validation.minlength', { min: 2 }) },
                    maxLength: { value: 90, errorMessage: translate('entity.validation.maxlength', { max: 90 }) },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="priceLabel" for="product-price">
                  <Translate contentKey="mySimpleShopApp.product.price">Price</Translate>
                </Label>
                <AvField
                  id="product-price"
                  data-cy="price"
                  type="string"
                  className="form-control"
                  name="price"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    min: { value: 0, errorMessage: translate('entity.validation.min', { min: 0 }) },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="descriptionLabel" for="product-description">
                  <Translate contentKey="mySimpleShopApp.product.description">Description</Translate>
                </Label>
                <AvInput
                  id="product-description"
                  data-cy="description"
                  type="textarea"
                  name="description"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <AvGroup>
                  <Label id="pictureLabel" for="picture">
                    <Translate contentKey="mySimpleShopApp.product.picture">Picture</Translate>
                  </Label>
                  <br />
                  {picture ? (
                    <div>
                      {pictureContentType ? (
                        <a onClick={openFile(pictureContentType, picture)}>
                          <img src={`data:${pictureContentType};base64,${picture}`} style={{ maxHeight: '100px' }} />
                        </a>
                      ) : null}
                      <br />
                      <Row>
                        <Col md="11">
                          <span>
                            {pictureContentType}, {byteSize(picture)}
                          </span>
                        </Col>
                        <Col md="1">
                          <Button color="danger" onClick={clearBlob('picture')}>
                            <FontAwesomeIcon icon="times-circle" />
                          </Button>
                        </Col>
                      </Row>
                    </div>
                  ) : null}
                  <input id="file_picture" data-cy="picture" type="file" onChange={onBlobChange(true, 'picture')} accept="image/*" />
                  <AvInput
                    type="hidden"
                    name="picture"
                    value={picture}
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                    }}
                  />
                </AvGroup>
              </AvGroup>
              <AvGroup>
                <AvGroup>
                  <Label id="specificationLabel" for="specification">
                    <Translate contentKey="mySimpleShopApp.product.specification">Specification</Translate>
                  </Label>
                  <br />
                  {specification ? (
                    <div>
                      {specificationContentType ? (
                        <a onClick={openFile(specificationContentType, specification)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                        </a>
                      ) : null}
                      <br />
                      <Row>
                        <Col md="11">
                          <span>
                            {specificationContentType}, {byteSize(specification)}
                          </span>
                        </Col>
                        <Col md="1">
                          <Button color="danger" onClick={clearBlob('specification')}>
                            <FontAwesomeIcon icon="times-circle" />
                          </Button>
                        </Col>
                      </Row>
                    </div>
                  ) : null}
                  <input id="file_specification" data-cy="specification" type="file" onChange={onBlobChange(false, 'specification')} />
                  <AvInput type="hidden" name="specification" value={specification} />
                </AvGroup>
              </AvGroup>
              <AvGroup>
                <Label id="categoryLabel" for="product-category">
                  <Translate contentKey="mySimpleShopApp.product.category">Category</Translate>
                </Label>
                <AvInput
                  id="product-category"
                  data-cy="category"
                  type="select"
                  className="form-control"
                  name="category"
                  value={(!isNew && productEntity.category) || 'Laptop'}
                >
                  <option value="Laptop">{translate('mySimpleShopApp.ProductCategory.Laptop')}</option>
                  <option value="Desktop">{translate('mySimpleShopApp.ProductCategory.Desktop')}</option>
                  <option value="Phone">{translate('mySimpleShopApp.ProductCategory.Phone')}</option>
                  <option value="Tablet">{translate('mySimpleShopApp.ProductCategory.Tablet')}</option>
                  <option value="Accessory">{translate('mySimpleShopApp.ProductCategory.Accessory')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="inventoryLabel" for="product-inventory">
                  <Translate contentKey="mySimpleShopApp.product.inventory">Inventory</Translate>
                </Label>
                <AvField
                  id="product-inventory"
                  data-cy="inventory"
                  type="string"
                  className="form-control"
                  name="inventory"
                  validate={{
                    required: { value: true, errorMessage: translate('entity.validation.required') },
                    min: { value: 0, errorMessage: translate('entity.validation.min', { min: 0 }) },
                    number: { value: true, errorMessage: translate('entity.validation.number') },
                  }}
                />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/product" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  productEntity: storeState.product.entity,
  loading: storeState.product.loading,
  updating: storeState.product.updating,
  updateSuccess: storeState.product.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  setBlob,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ProductUpdate);

// src/main/webapp/app/entities/product/product-update.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiDataUtils, JhiFileLoadError, JhiEventManager, JhiEventWithContent } from 'ng-jhipster';

import { IProduct, Product } from 'app/shared/model/product.model';
import { ProductService } from './product.service';
import { AlertError } from 'app/shared/alert/alert-error.model';

@Component({
  selector: 'bpf-product-update',
  templateUrl: './product-update.component.html',
})
export class ProductUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required, Validators.minLength(2), Validators.maxLength(90)]],
    price: [null, [Validators.required, Validators.min(0)]],
    description: [null, [Validators.required]],
    picture: [null, [Validators.required]],
    pictureContentType: [],
    specification: [],
    specificationContentType: [],
    category: [],
    inventory: [null, [Validators.required, Validators.min(0)]],
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected productService: ProductService,
    protected elementRef: ElementRef,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ product }) => {
      this.updateForm(product);
    });
  }

  updateForm(product: IProduct): void {
    this.editForm.patchValue({
      id: product.id,
      name: product.name,
      price: product.price,
      description: product.description,
      picture: product.picture,
      pictureContentType: product.pictureContentType,
      specification: product.specification,
      specificationContentType: product.specificationContentType,
      category: product.category,
      inventory: product.inventory,
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  setFileData(event: any, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe(null, (err: JhiFileLoadError) => {
      this.eventManager.broadcast(
        new JhiEventWithContent<AlertError>('mySimpleShopApp.error', { ...err, key: 'error.file.' + err.key })
      );
    });
  }

  clearInputImage(field: string, fieldContentType: string, idInput: string): void {
    this.editForm.patchValue({
      [field]: null,
      [fieldContentType]: null,
    });
    if (this.elementRef && idInput && this.elementRef.nativeElement.querySelector('#' + idInput)) {
      this.elementRef.nativeElement.querySelector('#' + idInput).value = null;
    }
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const product = this.createFromForm();
    if (product.id !== undefined) {
      this.subscribeToSaveResponse(this.productService.update(product));
    } else {
      this.subscribeToSaveResponse(this.productService.create(product));
    }
  }

  private createFromForm(): IProduct {
    return {
      ...new Product(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      price: this.editForm.get(['price'])!.value,
      description: this.editForm.get(['description'])!.value,
      pictureContentType: this.editForm.get(['pictureContentType'])!.value,
      picture: this.editForm.get(['picture'])!.value,
      specificationContentType: this.editForm.get(['specificationContentType'])!.value,
      specification: this.editForm.get(['specification'])!.value,
      category: this.editForm.get(['category'])!.value,
      inventory: this.editForm.get(['inventory'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProduct>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="bpf-product-heading" jhiTranslate="mySimpleShopApp.product.home.createOrEditLabel">Create or edit a Product</h2>
            <div>
                <bpf-alert-error></bpf-alert-error>
                <div class="form-group" [hidden]="!product.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                    <div *ngIf="editForm.get('name').invalid && (editForm.get('name').dirty || editForm.get('name').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.minlength" jhiTranslate="entity.validation.minlength" [translateValues]="{ min: 2 }">
                        This field is required to be at least 2 characters.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.maxlength" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: 90 }">
                        This field cannot be longer than 90 characters.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.price" for="field_price">Price</label>
                    <input type="number" class="form-control" name="price" id="field_price"
                           formControlName="price"/>
                    <div *ngIf="editForm.get('price').invalid && (editForm.get('price').dirty || editForm.get('price').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('price').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('price').errors.min" jhiTranslate="entity.validation.min" [translateValues]="{ min: 0 }">
                            This field should be at least 0.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('price')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.description" for="field_description">Description</label>
                    <textarea class="form-control" name="description" id="field_description"
                              formControlName="description"></textarea>
                    <div *ngIf="editForm.get('description').invalid && (editForm.get('description').dirty || editForm.get('description').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('description').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.picture" for="field_picture">Picture</label>
                    <div>
                        <img [src]="'data:' + editForm.get('pictureContentType').value + ';base64,' + editForm.get('picture').value" style="max-height: 100px;" *ngIf="editForm.get('picture').value" alt="product image"/>
                        <div *ngIf="editForm.get('picture').value" class="form-text text-danger clearfix">
                            <span class="pull-left">{{editForm.get('pictureContentType').value}}, {{byteSize(editForm.get('picture').value)}}</span>
                            <button type="button" (click)="clearInputImage('picture', 'pictureContentType', 'fileImage')" class="btn btn-secondary btn-xs pull-right">
                                <fa-icon [icon]="'times'"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_picture" (change)="setFileData($event, 'picture', true)" accept="image/*" jhiTranslate="entity.action.addimage"/>
                    </div>
                    <input type="hidden" class="form-control" name="picture" id="field_picture"
                           formControlName="picture"/>
                    <input type="hidden" class="form-control" name="pictureContentType" id="field_pictureContentType"
                           formControlName="pictureContentType" />
                    <div *ngIf="editForm.get('picture').invalid && (editForm.get('picture').dirty || editForm.get('picture').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('picture').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.specification" for="field_specification">Specification</label>
                    <div>
                        <div *ngIf="editForm.get('specification').value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('specificationContentType').value, editForm.get('specification').value)" jhiTranslate="entity.action.open">open</a><br>
                            <span class="pull-left">{{editForm.get('specificationContentType').value}}, {{byteSize(editForm.get('specification').value)}}</span>
                            <button type="button" (click)="editForm.patchValue({specification: null});editForm.patchValue({specificationContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon [icon]="'times'"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_specification" (change)="setFileData($event, 'specification', false)" jhiTranslate="entity.action.addblob"/>
                    </div>
                    <input type="hidden" class="form-control" name="specification" id="field_specification"
                           formControlName="specification"/>
                    <input type="hidden" class="form-control" name="specificationContentType" id="field_specificationContentType"
                           formControlName="specificationContentType" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.category" for="field_category">Category</label>
                    <select class="form-control" name="category" formControlName="category" id="field_category">
                        <option value="Laptop">{{'mySimpleShopApp.ProductCategory.Laptop' | translate}}</option>
                        <option value="Desktop">{{'mySimpleShopApp.ProductCategory.Desktop' | translate}}</option>
                        <option value="Phone">{{'mySimpleShopApp.ProductCategory.Phone' | translate}}</option>
                        <option value="Tablet">{{'mySimpleShopApp.ProductCategory.Tablet' | translate}}</option>
                        <option value="Accessory">{{'mySimpleShopApp.ProductCategory.Accessory' | translate}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mySimpleShopApp.product.inventory" for="field_inventory">Inventory</label>
                    <input type="number" class="form-control" name="inventory" id="field_inventory"
                           formControlName="inventory"/>
                    <div *ngIf="editForm.get('inventory').invalid && (editForm.get('inventory').dirty || editForm.get('inventory').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('inventory').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('inventory').errors.min" jhiTranslate="entity.validation.min" [translateValues]="{ min: 0 }">
                            This field should be at least 0.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('inventory')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div *ngIf="editForm.get('order').invalid && (editForm.get('order').dirty || editForm.get('order').touched)">
                    <small class="form-text text-danger"
                           *ngIf="editForm.get('order').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
